Repository fuxingloh/vue-horizontal-list, pull requests merged in 2020-11, with the labels that each got.

#38 Triage, CI and Publish GitHub Actions workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/triage.yml
Labels: chore

#40 Added prettier for dev and in CI
  .github/auto_assign.yml
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  .prettierignore
  package.json
  yarn.lock
Labels: chore

#41 Slots for start/end and options.position.start
  README.md
  babel.config.js
  build/rollup.config.js
  dev/serve.js
  dev/serve.vue
  src/entry.js
  src/vue-horizontal-list.vue
Labels: fix

#42 Refactor examples/*
  dev/serve.vue
  examples/auto-play.vue
  examples/full-width.vue
  examples/item-customization.vue
  examples/left-right-slot.vue
  examples/position-start.vue
  examples/responsive.vue
  examples/serve.js
  examples/serve.vue
  examples/simple.vue
  package.json
  src/vue-horizontal-list.vue
Labels: chore

#43 Added customizable nav prev and start icon
  examples/examples.vue
  examples/nav-prev-next-slot.vue
  examples/serve.js
  src/vue-horizontal-list.vue
Labels: feature

#46 Prettier will only warn and fail instead of crashing
  .github/workflows/ci.yml
Labels: fix

#47 Added gh-pages deploy
  .github/workflows/gh-pages.yml
  .gitignore
  .prettierignore
  package.json
  vue.config.js
  yarn.lock
Labels: feature

#48 Changed to use a managed action
  .github/workflows/gh-pages.yml
Labels: fix

#50 Moved examples from nuxt-app into this repo
  examples/auto-play.vue
  examples/image-five.vue
  examples/image-four.vue
  examples/image-three.vue
  examples/image-two.vue
  examples/index.vue
  examples/left-right-slot.vue
  examples/nav-prev-next-slot.vue
  examples/serve.js
Labels: chore

#51 Updated README.md
  README.md
Labels: chore

#52 Implement drag features
  examples/draggable-items.vue
  examples/index.vue
  src/vue-horizontal-list.vue
Labels: feature

#54 Revert "Implement drag features (#52)"
  examples/draggable-items.vue
  examples/index.vue
  src/vue-horizontal-list.vue
Labels: fix
